import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(rootDir, "package.json"), "utf-8"));

const out = `// AUTO-GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand
export const CORE_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(join(rootDir, "src/internal/version.ts"), out, "utf-8");
