import type { DiscoveredPlugin } from "./scan-plugins.js";
import type { ExtractedHook, ExtractedMethod } from "./extract-wefter-plugin.js";

export interface PluginExtraction {
  methods: ExtractedMethod[];
  hooks: ExtractedHook[];
}

export function classNameFor(pluginName: string): string {
  const pascal = pluginName
    .split(/[-_]+/)
    .flatMap((part) => part.split(/(?=[A-Z])/))
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
  return `${pascal}Plugin`;
}

function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function generateMethodDispatch(className: string, methods: ExtractedMethod[]): string {
  const cases = methods.map((m) => `            "${m.name}" -> plugin.${m.name}(payload, callback)`).join("\n");
  return [
    `class ${className}Dispatch(private val plugin: ${className}) : NativeModule {`,
    `    override fun invoke(method: String, payload: JSONObject, callback: (Result<Any>) -> Unit) {`,
    `        when (method) {`,
    cases,
    `            else -> callback(Result.failure(WefterError("UNKNOWN_METHOD", "No such method: $method")))`,
    `        }`,
    `    }`,
    `}`,
  ].join("\n");
}

export function generateRegistryKotlin(
  plugins: DiscoveredPlugin[],
  packageName: string,
  extraction: Map<string, PluginExtraction> = new Map(),
): string {
  const dispatchClasses: string[] = [];
  const registrationLines: string[] = [];

  for (const plugin of plugins) {
    const name = plugin.manifest.name;
    const className = classNameFor(name);
    const ext = extraction.get(name) ?? { methods: [], hooks: [] };

    if (ext.methods.length === 0) {
      registrationLines.push(`        dispatcher.register("${name}", ${className}())`);
      continue;
    }

    dispatchClasses.push(generateMethodDispatch(className, ext.methods));

    const varName = lowerFirst(className);
    registrationLines.push(`        val ${varName} = ${className}(context, dispatcher)`);
    registrationLines.push(`        dispatcher.register("${name}", ${className}Dispatch(${varName}))`);
    registrationLines.push(`        WefterBridge.register("${name}", ${varName})`);
    for (const hook of ext.hooks) {
      registrationLines.push(
        `        dispatcher.subscribeHook("${hook.hookName}") { ${varName}.${hook.methodName}() }`,
      );
    }
  }

  const dispatchSection = dispatchClasses.length > 0 ? `${dispatchClasses.join("\n\n")}\n\n` : "";

  return `
// AUTO-GENERATED by wefter sync — do not edit by hand
package ${packageName}

import android.content.Context
import org.json.JSONObject

${dispatchSection}object GeneratedRegistry {
    fun registerAll(context: Context, dispatcher: BridgeDispatcher) {
${registrationLines.join("\n")}
    }
}
`.trim();
}
