import type { DiscoveredPlugin } from './scan-plugins.js';
import type { ExtractedHook, ExtractedMethod } from './extract-wefter-plugin-swift.js';
import { classNameFor } from './codegen-android.js';

export interface PluginExtractionSwift {
  methods: ExtractedMethod[];
  hooks: ExtractedHook[];
}

function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function generateMethodDispatch(className: string, methods: ExtractedMethod[]): string {
  const cases = methods
    .map((m) => `        case "${m.name}":\n            try plugin.${m.name}(payload: payload, callback: callback)`)
    .join('\n');
  return [
    `final class ${className}Dispatch: NativeModule {`,
    `    private let plugin: ${className}`,
    `    init(plugin: ${className}) { self.plugin = plugin }`,
    ``,
    `    func invoke(method: String, payload: [String: Any], callback: @escaping (Result<Any, Error>) -> Void) throws {`,
    `        switch method {`,
    cases,
    `        default:`,
    `            callback(.failure(WefterError(code: "UNKNOWN_METHOD", message: "No such method: \\(method)")))`,
    `        }`,
    `    }`,
    `}`,
  ].join('\n');
}

export function generateRegistrySwift(
  plugins: DiscoveredPlugin[],
  extraction: Map<string, PluginExtractionSwift> = new Map(),
): string {
  const dispatchClasses: string[] = [];
  const registrationLines: string[] = [];

  for (const plugin of plugins) {
    const name = plugin.manifest.name;
    const ext = extraction.get(name);
    if (!ext) continue;

    const className = classNameFor(name);
    dispatchClasses.push(generateMethodDispatch(className, ext.methods));

    const varName = lowerFirst(className);
    registrationLines.push(
      `        let ${varName} = ${className}(dispatcher: dispatcher, viewController: viewController)`,
    );
    registrationLines.push(`        dispatcher.register("${name}", module: ${className}Dispatch(plugin: ${varName}))`);
    for (const hook of ext.hooks) {
      registrationLines.push(`        dispatcher.subscribeHook("${hook.hookName}") { ${varName}.${hook.methodName}() }`);
    }
  }

  const dispatchSection = dispatchClasses.length > 0 ? `${dispatchClasses.join('\n\n')}\n\n` : '';

  return `
// AUTO-GENERATED by wefter sync — do not edit by hand
import Foundation
import UIKit

${dispatchSection}enum GeneratedRegistry {
    static func registerAll(dispatcher: BridgeDispatcher, viewController: UIViewController) {
${registrationLines.join('\n')}
    }
}
`.trim();
}
