import type { DiscoveredPlugin } from "./scan-plugins.js";

interface SpmDependency {
  url: string;
  from: string;
  product: string;
}

function packageIdentity(url: string): string {
  const lastSegment = url.replace(/\/+$/, "").split("/").pop() ?? url;
  return lastSegment.replace(/\.git$/, "");
}

export function generateNativeDependenciesPackage(plugins: DiscoveredPlugin[]): string {
  const deps: SpmDependency[] = [];
  for (const plugin of plugins) {
    for (const dep of plugin.manifest.nativeDependencies?.ios?.spm ?? []) {
      deps.push(dep);
    }
  }

  const uniqueByUrl = new Map<string, SpmDependency>();
  for (const dep of deps) uniqueByUrl.set(dep.url, dep);

  const dependencyLines = [...uniqueByUrl.values()]
    .map((d) => `        .package(url: "${d.url}", from: "${d.from}"),`)
    .join("\n");

  const productKeys = new Set<string>();
  const productLines: string[] = [];
  for (const dep of deps) {
    const identity = packageIdentity(dep.url);
    const key = `${identity}:${dep.product}`;
    if (productKeys.has(key)) continue;
    productKeys.add(key);
    productLines.push(`                .product(name: "${dep.product}", package: "${identity}"),`);
  }

  return `
// swift-tools-version:5.9
// AUTO-GENERATED by wefter sync — do not edit by hand
import PackageDescription

let package = Package(
    name: "NativeDependencies",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "NativeDependencies", targets: ["NativeDependencies"])
    ],
    dependencies: [
${dependencyLines}
    ],
    targets: [
        .target(
            name: "NativeDependencies",
            dependencies: [
${productLines.join("\n")}
            ]
        )
    ]
)
`.trim();
}
