import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const cliDir = dirname(dirname(fileURLToPath(import.meta.url)));
const coreDir = join(cliDir, "../core");

const cliPkg = JSON.parse(readFileSync(join(cliDir, "package.json"), "utf-8"));
const corePkg = JSON.parse(readFileSync(join(coreDir, "package.json"), "utf-8"));

const out = `// AUTO-GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand
export const CLI_VERSION = ${JSON.stringify(cliPkg.version)};
export const CORE_VERSION = ${JSON.stringify(corePkg.version)};
`;

mkdirSync(join(cliDir, "src/internal"), { recursive: true });
writeFileSync(join(cliDir, "src/internal/version.ts"), out, "utf-8");
