// AUTO-GENERATED by wefter sync — do not edit by hand
import Foundation
import UIKit

enum GeneratedRegistry {
    static func registerAll(dispatcher: BridgeDispatcher, viewController: UIViewController) {

    }
}
