// AUTO-GENERATED by wefter sync — do not edit by hand
package dev.wefter.bridge

import android.content.Context
import org.json.JSONObject

object GeneratedRegistry {
    fun registerAll(context: Context, dispatcher: BridgeDispatcher) {

    }
}
